from PyQt5 import QtCore ,QtGui, QtWidgets
import pypyodbc



class Ui_MainWindow(object):
    def tabmenuaktif(self):
        self.tab_2.setEnabled(True)
        self.tab_3.setEnabled(True)
        self.tab_4.setEnabled(True)

    def mesaj(self , baslik="UYARI" , icerik="SQL Bağlantısı Sağlandı"):
        self.msj = QtWidgets.QMessageBox()
        self.msj.setWindowTitle(baslik)
        self.msj.setText(icerik)
        self.msj.setStandardButtons(QtWidgets.QMessageBox.Ok)
        self.msj.exec_()

    def baglan(self):
        try:
            self.server = self.lineEdit.text()
            self.db = self.lineEdit_2.text()
            self.kadi = self.lineEdit_3.text()
            self.sifre = self.lineEdit_4.text()

            self.conn_metni = (
                'Driver={SQL Server};'
                'Server=' + self.server + ';'
                'Database=' + self.db + ';'
                'UID=' + self.kadi + ';'
                'PWD=' + self.sifre + ';')

            self.conn = pypyodbc.connect(self.conn_metni)

            self.cursor = self.conn.cursor()

            self.mesaj()
            self.tabmenuaktif()

        except:
            self.mesaj("UYARI" , "SQL Bağlantısı Kurulamadı")


    def hesapyazimgerial(self):
        cekno = self.lineEdit_5.text()
        self.cursor.execute("update orderheaders set FiscalKey='',FiscalStatus=0,OrderStatus=1,ingenico='' where OrderID = {}".format(cekno))
        self.cursor.execute("update orderpayments set lineDeleted=1 where OrderID = {}".format(cekno))
        self.cursor.commit()
        self.mesaj("Uyarı" , "İşlem Tamamlandı" )
    def raporseviyesi(self):
        seviye = self.comboBox.currentText()
        self.cursor.execute("UPDATE Reports SET SecurityLevel= {} ".format(seviye))
        self.cursor.commit()
        self.mesaj("Uyarı", "İşlem Tamamlandı")

    def fiscal(self):
        if (self.radiobuton.isChecked()):
            cekno = self.lineEdit_6.text()
            self.cursor.execute("update orderheaders set FiscalStatus=1 where OrderID= {}".format(cekno))
            self.cursor.commit()
            self.mesaj("Uyarı", "İşlem Tamamlandı")
        elif(self.radiobuton2.isChecked()):
            cekno = self.lineEdit_6.text()
            self.cursor.execute("update orderheaders set FiscalStatus=0 where OrderID= {}".format(cekno))
            self.cursor.commit()
            self.mesaj("Uyarı", "İşlem Tamamlandı")
        else:
            self.mesaj("Uyarı" , "Hatalı İşlem")

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(525, 336)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 501, 271))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(60, 50, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(60, 80, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(60, 109, 141, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(60, 142, 141, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(280, 49, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(280, 78, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_3.setGeometry(QtCore.QRect(280, 108, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_4.setGeometry(QtCore.QRect(280, 139, 113, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(57, 172, 341, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.baglan)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tab_2.setDisabled(True)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 110, 151, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.hesapyazimgerial)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(160, 60, 151, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(77, 64, 47, 13))
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tab_3.setDisabled(True)
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(80, 70, 91, 21))
        self.label_6.setObjectName("label_6")
        self.comboBox = QtWidgets.QComboBox(self.tab_3)
        self.comboBox.setGeometry(QtCore.QRect(170, 70, 91, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_3.setGeometry(QtCore.QRect(170, 100, 91, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.raporseviyesi)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tab_4.setDisabled(True)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_4.setGeometry(QtCore.QRect(190, 110, 121, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.fiscal)
        self.label_7 = QtWidgets.QLabel(self.tab_4)
        self.label_7.setGeometry(QtCore.QRect(60, 52, 101, 20))
        self.label_7.setObjectName("label_7")
        self.radiobuton = QtWidgets.QRadioButton(self.tab_4)
        self.radiobuton.setGeometry(QtCore.QRect(60, 82, 101, 20))
        self.radiobuton.setObjectName("radiobuton")
        self.radiobuton2 = QtWidgets.QRadioButton(self.tab_4)
        self.radiobuton2.setGeometry(QtCore.QRect(180 , 82, 101, 20))
        self.radiobuton2.setObjectName("radiobuton_2")
        self.label_9 = QtWidgets.QLabel(self.tab_4)
        self.label_9.setGeometry(QtCore.QRect(200, 82, 101, 20))
        self.label_9.setObjectName("label_9")
        self.label_8 = QtWidgets.QLabel(self.tab_4)
        self.label_8.setGeometry(QtCore.QRect(84, 82, 101, 20))
        self.label_8.setObjectName("label_8")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_6.setGeometry(QtCore.QRect(190, 50, 121, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        #self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_4)
        #self.lineEdit_7.setGeometry(QtCore.QRect(190, 80, 121, 20))
        #self.lineEdit_7.setObjectName("lineEdit_7")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 525, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "SERVER"))
        self.label_2.setText(_translate("MainWindow", "DATABASE"))
        self.label_3.setText(_translate("MainWindow", "DATABASE KULLANICI ADI"))
        self.label_4.setText(_translate("MainWindow", "DATABASE KULLANICI ŞİFRE"))
        self.pushButton.setText(_translate("MainWindow", "Bağlan"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "SQL Bağlantı"))
        self.pushButton_2.setText(_translate("MainWindow", "Hesap Yazımı Geri Al"))
        self.label_5.setText(_translate("MainWindow", "ÇEK NO"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Çek Aç"))
        self.label_6.setText(_translate("MainWindow", "Rapor Seviyesi"))
        self.comboBox.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox.setItemText(9, _translate("MainWindow", "10"))
        self.pushButton_3.setText(_translate("MainWindow", "Değiştir"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Rapor Seviyesi"))
        self.pushButton_4.setText(_translate("MainWindow", "Değiştir"))
        self.label_7.setText(_translate("MainWindow", "Çek No"))
        self.label_8.setText(_translate("MainWindow", "Fiscal Ekle"))
        self.label_9.setText(_translate("MainWindow", "Fiscal Kaldır"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Fiscal Ayarla"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
